global:
  pullSecrets: []
  imageRegistry: ""
image:
  registry: ghcr.io
  repository: hierynomus/outrider
  tag: 0.6.0
  pullPolicy: IfNotPresent


serviceAccount:
  enabled: true
  name: outrider

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

fullnameOverride: ""
nameOverride: ""

logLevel: "info"
defaultTargetNamespace: ""