apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "outrider.fullname" . }}
  labels:
    {{- include "outrider.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "outrider.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "outrider.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- if .Values.global.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.pullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
        - name: outrider
          image: {{ default .Values.image.registry .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: []
          env:
            - name: RUST_LOG
              value: {{ .Values.logLevel | default "warn" }}
            - name: DEFAULT_TARGET_NAMESPACE
              value: {{ .Values.defaultTargetNamespace }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
