{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "outrider.serviceAccountName" . }}
  labels:
    {{- include "outrider.labels" . | nindent 4 }}
{{- end -}}
